fix: Lots of UI fixes.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,7 @@
-npx lint-staged
+#!/usr/bin/env sh
+
+npx lint-staged || {
+  echo "Pre-commit hook failed. Restoring staged changes from stash..."
+  git stash pop
+  exit 1
+}
